In [1]:
#### importing numpy
import numpy as np

In [2]:
#### Creating arrays

In [7]:
#### 1-D Array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.shape

(5,)

In [6]:
a.ndim

1

In [8]:
#### 2-D Array
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b.shape

(2, 3)

In [10]:
b.ndim

2

In [14]:
#### 3-D Array
c= np.array([[[1,2,3], [4,5,6], [7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [12]:
c.shape

(1, 3, 3)

In [13]:
c.ndim

3

In [15]:
#### np.arange

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = np.arange(1,10)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c = np.arange(1, 10, 2)
c

array([1, 3, 5, 7, 9])

In [23]:
#### np.reshape

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
a.ndim

2

In [29]:
#### Changing datatype

In [30]:
a.astype('float64')

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [31]:
#### where condition

In [32]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
np.where(a<6)

(array([0, 0, 0, 0, 0, 1], dtype=int64),
 array([0, 1, 2, 3, 4, 0], dtype=int64))

In [34]:
np.where(a<=4, a, a*10)

array([[ 0,  1,  2,  3,  4],
       [50, 60, 70, 80, 90]])

In [35]:
#### empty array

In [36]:
np.empty([2,2])

array([[2.12199579e-314, 1.56603289e-311],
       [5.27662110e-321, 1.56603289e-311]])

In [37]:
#### ones array

In [38]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [39]:
np.ones([2,2], dtype = 'int')

array([[1, 1],
       [1, 1]])

In [40]:
#### zeros array

In [41]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [42]:
np.zeros([2,2], dtype = 'int')

array([[0, 0],
       [0, 0]])

In [43]:
#### full arrray

In [44]:
np.full([2,2], 10)

array([[10, 10],
       [10, 10]])

In [45]:
#### unique elements

In [46]:
a = np.array([1,2,3,1,2,4,5,3,7,6])

In [48]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
x,y = np.unique(a, return_index = True)

In [53]:
x # unique values

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
y # indexes of unique values

array([0, 1, 2, 5, 6, 9, 8], dtype=int64)

In [57]:
x,y,z = np.unique(a, return_index = True, return_counts = True)

In [58]:
z # count of each unique value in the array

array([2, 2, 2, 1, 1, 1, 1], dtype=int64)

In [59]:
b = np.array([1,2,np.nan,3,1,2,4, np.nan,5,3,np.nan,7,6, np.nan])
b

array([ 1.,  2., nan,  3.,  1.,  2.,  4., nan,  5.,  3., nan,  7.,  6.,
       nan])

In [60]:
np.unique(b)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

In [61]:
np.unique(b, return_index = True, return_counts = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan]),
 array([ 0,  1,  3,  6,  8, 12, 11,  2], dtype=int64),
 array([2, 2, 2, 1, 1, 1, 1, 4], dtype=int64))

In [64]:
np.unique(b, return_index = True, return_counts = True, equal_nan = True)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan]),
 array([ 0,  1,  3,  6,  8, 12, 11,  2], dtype=int64),
 array([2, 2, 2, 1, 1, 1, 1, 4], dtype=int64))

In [65]:
np.unique(b, return_index = True, return_counts = True, equal_nan = False)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan, nan, nan, nan]),
 array([ 0,  1,  3,  6,  8, 12, 11,  2,  7, 10, 13], dtype=int64),
 array([2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [66]:
#### np.any

In [67]:
a = np.array([0,1,2,3,4])   # 1D array

In [68]:
np.any(a)

True

In [69]:
np.any([True, False, False])

True

In [70]:
b = np.array([[0,0,0], [4,5,6]])   # 2D array
b

array([[0, 0, 0],
       [4, 5, 6]])

In [71]:
np.any(b)

True

In [72]:
c = np.array([[[0,0,0], [4,5,6], [1,2,3]]])   # 3D array
c

array([[[0, 0, 0],
        [4, 5, 6],
        [1, 2, 3]]])

In [73]:
np.any(c)

True

In [81]:
a

array([0, 1, 2, 3, 4])

In [80]:
np.any(a, axis = 0)

True

In [82]:
b

array([[0, 0, 0],
       [4, 5, 6]])

In [83]:
np.any(b, axis = 0)   # columns

array([ True,  True,  True])

In [84]:
np.any(b, axis = 1)   # rows

array([False,  True])

In [86]:
c

array([[[0, 0, 0],
        [4, 5, 6],
        [1, 2, 3]]])

In [87]:
np.any(c, axis = 0)   

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [88]:
np.any(c, axis = 1)   # columns

array([[ True,  True,  True]])

In [89]:
np.any(c, axis = 2)   # rows

array([[False,  True,  True]])

In [90]:
#### np.all

In [91]:
a = np.array([0,1,2,3,4])   # 1D array

In [92]:
np.all(a)

False

In [93]:
np.all([True, False, False])

False

In [94]:
b = np.array([[0,0,0], [4,5,6]])   # 2D array
b

array([[0, 0, 0],
       [4, 5, 6]])

In [95]:
np.all(b)

False

In [96]:
c = np.array([[[0,0,0], [4,5,6], [1,2,3]]])   # 3D array
c

array([[[0, 0, 0],
        [4, 5, 6],
        [1, 2, 3]]])

In [97]:
np.all(c)

False

In [99]:
b

array([[0, 0, 0],
       [4, 5, 6]])

In [98]:
np.all(b, axis = 0)   # columns

array([False, False, False])

In [101]:
np.all(b, axis = 1)   # rows

array([False,  True])

In [102]:
c

array([[[0, 0, 0],
        [4, 5, 6],
        [1, 2, 3]]])

In [103]:
np.all(c, axis = 0)   

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [104]:
np.all(c, axis = 1)   # columns

array([[False, False, False]])

In [105]:
np.all(c, axis = 2)   # rows

array([[False,  True,  True]])

In [106]:
#### Transpose

In [107]:
a=np.arange(10).reshape(5,2)

In [108]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
a.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [110]:
#### flatten

In [111]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [114]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
#### slicing

In [116]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [117]:
a[1:4, 0:1]

array([[2],
       [4],
       [6]])

In [118]:
#### np.max

In [120]:
np.max(a)

9

In [121]:
#### np.min

In [122]:
np.min(a)

0

In [123]:
#### np.argmax

In [125]:
a = np.array([5,3,9,1,6,2,0])

In [126]:
np.argmax(a)

2

In [127]:
b = np.array([[[5,2,9], [10,2,6], [0,19,3]]])

In [128]:
b

array([[[ 5,  2,  9],
        [10,  2,  6],
        [ 0, 19,  3]]])

In [129]:
np.argmax(b)

7

In [130]:
#### np.sort

In [131]:
np.sort(a)

array([0, 1, 2, 3, 5, 6, 9])

In [132]:
np.sort(b)

array([[[ 2,  5,  9],
        [ 2,  6, 10],
        [ 0,  3, 19]]])

In [133]:
#### np.argsort

In [134]:
np.argsort(a)

array([6, 3, 5, 1, 0, 4, 2], dtype=int64)

In [135]:
np.argsort(b)

array([[[1, 0, 2],
        [1, 2, 0],
        [0, 2, 1]]], dtype=int64)

In [137]:
#### matmul

In [140]:
a = np.arange(6).reshape(3,2)
b = np.arange(7,13).reshape(2,3)
a,b

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]))

In [141]:
np.matmul(a,b)

array([[10, 11, 12],
       [44, 49, 54],
       [78, 87, 96]])

In [142]:
#### np.dot

In [143]:
np.dot(a, b)

array([[10, 11, 12],
       [44, 49, 54],
       [78, 87, 96]])

In [144]:
#### np.vectorize

In [147]:
import math

In [163]:
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
math.log(1)

0.0

In [158]:
math.log(9)

2.1972245773362196

In [159]:
math.log(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [161]:
log_func = np.vectorize(math.log)

In [164]:
log_func(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [186]:
sum = 0
def add(a,b):
    sum = a+b
    return sum
res = np.vectorize(add)
a = np.arange(1, 20, 4)
b = np.arange(1, 10, 2)
res(a,b )

array([ 2,  8, 14, 20, 26])

In [5]:
def product(a,b):
    res = a*b
    return res
a = np.arange(1, 20, 4)
b = np.arange(1, 10, 2)
ans = np.vectorize(product)
a,b,ans(a,b)

(array([ 1,  5,  9, 13, 17]),
 array([1, 3, 5, 7, 9]),
 array([  1,  15,  45,  91, 153]))

In [9]:
####  Copying data -- Shallow copy vs Deep copy

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b=a   # Shallow copy -- any changes in one variable will be reflected in other variable

In [13]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b[0] = 100

In [15]:
b

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
a[0] = 0

In [18]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c = a.copy()  # Deep copy -- changes in one variable will not be reflected in other variable

In [23]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
c[0] = 10
c

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [25]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a[0] = 55

In [28]:
print('a is: ', a)
print('b is: ', b, '-- Shallow Copy')
print('c is: ',c, '-- Deep copy')

a is:  [55  1  2  3  4  5  6  7  8  9]
b is:  [55  1  2  3  4  5  6  7  8  9] -- Shallow Copy
c is:  [10  1  2  3  4  5  6  7  8  9] -- Deep copy


In [38]:
#### split -- hsplit and vsplit

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.split(a, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [35]:
np.split(a, [3,5,7])

[array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8, 9])]

In [39]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
np.hsplit(a, 2) # axis = 1, along columns

[array([[0],
        [2],
        [4]]),
 array([[1],
        [3],
        [5]])]

In [44]:
a= np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [46]:
a= np.arange(10)

In [48]:
np.hsplit(a, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [56]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
np.hsplit(a, 2)

[array([[[0, 1]],
 
        [[4, 5]]]),
 array([[[2, 3]],
 
        [[6, 7]]])]

In [57]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.vsplit(a, 2)  # axis = 0, along rows

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.vsplit(a, 2) # works for 2D array or more

ValueError: vsplit only works on arrays of 2 or more dimensions

In [62]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [63]:
np.vsplit(a, 2)

[array([[[0, 1],
         [2, 3]]]),
 array([[[4, 5],
         [6, 7]]])]

In [64]:
#### Stacking

In [65]:
a = np.arange(1, 10)
b = np.arange(11,20)

In [68]:
np.vstack([a,b]) # stacks vertically along rows, both array should have equal number of columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [69]:
np.hstack([a,b]) # stacks horizontally along the column, both array should have equal number of rows

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [70]:
np.concatenate([a,b])  # same as hstack

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [71]:
#### tile

In [74]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [75]:
np.tile(a, [2, 3])

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]])

In [76]:
#### expand_dims

In [93]:
a = np.arange(6)

In [94]:
a.ndim

1

In [95]:
a = np.expand_dims(a, axis = 0)

In [96]:
a.ndim

2

In [97]:
a = np.expand_dims(a, axis = 1)

In [98]:
a

array([[[0, 1, 2, 3, 4, 5]]])

In [99]:
a.ndim

3

In [86]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [89]:
a = np.expand_dims(a, axis = 0)
a.ndim

3

In [90]:
#### squeeze

In [100]:
a

array([[[0, 1, 2, 3, 4, 5]]])

In [102]:
np.squeeze(a).ndim

1

In [3]:
'''Question:
Given a list of birds and their corresponding age, 
calculate the mean age of the Crane bird (rounded off to 2 decimal points)
'''

'Question:\nGiven a list of birds and their corresponding age, \ncalculate the mean age of the Crane bird (rounded off to 2 decimal points)\n'

In [2]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  
         'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [7]:
mask = birds[birds == 'Cranes']

In [9]:
crane_ages = age[birds == 'Cranes']

In [11]:
mean_age = np.mean(crane_ages)

In [12]:
mean_age = np.round(mean_age, 2)
mean_age

5.5

In [13]:
'''Question
Given an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º.
'''

'Question\nGiven an array in form of a matrix of size (n, n), rotate the matrix clockwise by 90º.\n'

In [14]:
arr  = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [15]:
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [20]:
arr.T[::, ::-1]

array([[[7],
        [4],
        [1]],

       [[8],
        [5],
        [2]],

       [[9],
        [6],
        [3]]])

In [21]:
'''Question
Given a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)
Find the oldest bird
'''

'Question\nGiven a list of birds and their corresponding age, return the name of birds sorted according to age (ascending)\n'

In [22]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  
         'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [28]:
age_sorted = np.argsort(age)
age_sorted

array([3, 7, 4, 2, 6, 5, 0, 8, 1, 9], dtype=int64)

In [31]:
res= []
for i in age_sorted:
    res.append(birds[i])
print(res)

['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes', 'spoonbills', 'Cranes', 'plovers', 'spoonbills']


In [34]:
oldest = birds[age_sorted[-1]]
oldest

'spoonbills'